# Generated by Django 5.1.6 on 2025-02-12 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=10000, verbose_name='Texto')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data e horário da mensagem')),
                ('eh_do_usuario', models.BooleanField(default=True, verbose_name='Mensagem do usuário?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
