# Generated by Django 5.1.6 on 2025-02-12 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='conversa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensagens', to='application.conversa'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversas', to=settings.AUTH_USER_MODEL),
        ),
    ]
