# Generated by Django 5.1.6 on 2025-03-12 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='nome',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Texto'),
        ),
    ]
