# Generated by Django 5.1.6 on 2025-02-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_mensagem_usuario_mensagem_conversa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversa',
            options={'verbose_name': 'Conversa', 'verbose_name_plural': 'Conversas'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
    ]
