# Generated by Django 5.1.6 on 2025-04-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
