# Generated by Django 5.1.6 on 2025-09-07 21:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_documento_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caput', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Caput')),
                ('artigo_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='application.artigo')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
        ),
        migrations.CreateModel(
            name='Inciso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Rótulo')),
                ('texto', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Texto')),
                ('artigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incisos', to='application.artigo')),
            ],
            options={
                'verbose_name': 'Inciso',
                'verbose_name_plural': 'Incisos',
            },
        ),
        migrations.CreateModel(
            name='Alinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Rótulo')),
                ('texto', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Texto')),
                ('inciso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alineas', to='application.inciso')),
            ],
            options={
                'verbose_name': 'Alínea',
                'verbose_name_plural': 'Alíneas',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Rótulo')),
                ('texto', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Texto')),
                ('alinea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='application.alinea')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Paragrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Rótulo')),
                ('texto', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Texto')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragrafos', to='application.artigo')),
            ],
            options={
                'verbose_name': 'Parágrafo',
                'verbose_name_plural': 'Parágrafos',
            },
        ),
        migrations.AddField(
            model_name='inciso',
            name='paragrafo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incisos', to='application.paragrafo'),
        ),
    ]
