# Generated by Django 5.1.6 on 2025-09-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_artigo_inciso_alinea_item_paragrafo_inciso_paragrafo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.JSONField()),
            ],
            options={
                'verbose_name': 'Documento JSON',
                'verbose_name_plural': 'Documentos JSON',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='alinea',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='artigo_pai',
        ),
        migrations.RemoveField(
            model_name='inciso',
            name='artigo',
        ),
        migrations.RemoveField(
            model_name='paragrafo',
            name='artigo',
        ),
        migrations.RemoveField(
            model_name='inciso',
            name='paragrafo',
        ),
        migrations.DeleteModel(
            name='Alinea',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Artigo',
        ),
        migrations.DeleteModel(
            name='Inciso',
        ),
        migrations.DeleteModel(
            name='Paragrafo',
        ),
    ]
