# Generated by Django 5.1.6 on 2025-04-12 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_documento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='conversa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='application.conversa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data e horário do upload'),
            preserve_default=False,
        ),
    ]
